### PR TITLE
Refactor: implement factory pattern for Effects

### PR DESCRIPTION
**Pull request by andidevi**
This enables
        - easy configuration of effects including adding new ones ;)
        - makes it more streamlined to write new effects
        - individual prices for effects
        - display string different from name

### CODE REVIEW

**Comment by Lonami** [comment]
Quite a few changes, will review when I have time thank you!

**Comment by andidevi** [comment]
I know, but it's less than it seems:

- the biggest part are IEffectFactory and the factories for the effects
- the factories also work as a Java Bean providing meta data like name and price 
- class Effect got removed
- the list of available effects is now in class Klooni without numbering or id, it's just the order in the array that counts
- playing sounds is now class Kooni too

**Comment by Lonami** [comment]
Several things:
- Not sure if you noticed but libGDX seems to use direct member access pretty often, as opposed to using getters and setters (which I find stupid for trivial stuff like this where you don't need that much control, this is not a library after all). But since you're using a factory I guess there's no other way.
- I'm not sure I like the idea of factories. It feels like so much boilerplate. Now when you want to create a effect you need to create two classes. I wish Java had a better way to do this, like `abstract static`. But no, you need an instance.

But… on the other hand I can see it gets rid of the hardcoded names, better supports things like setting a price and so on. I just wish there was a more straightforward way to do this rather than using classes to create instances of other classes.

I'd like to discuss this a bit more but first I'm pushing a automatic code reformat to your branch.

**Comment by andidevi** [comment]
There are good reason to follow Patterns, as many people have been thinking about, how to implement things most straightforward. Programming feels more abstract if you aren't used to them but if you can identify the patterns, its more like building a wall out of bricks.
https://en.wikipedia.org/wiki/Software_design_pattern

- factories are necessary here, as they are the only way to move the creation of effects behind the interface.
- the interface is necessary to don't have to do the ugly switch. 
- it is the same for the effect meta data, you need to have an interface to write a generic display component
- libGDX does use direct member access to speed things up a little and most time this is internal use. But we aren't on a time critical path here. 
- This is also a real interface to let people add effects, not only one in java terms.

One could make the effect an inner class of the factory, thats how it is done usually. But I decided against it, to keep the necessary level of programming skills low to give more people the chance to implement effects.

I don't even feel bad about the boiler plates. This is how java works and it is written by the IDE aka Adroid Studio. 

Edit: how to enable it? but I'll throw away my branch if you merge and keep stick to your master.

**Comment by Lonami** [comment]
> But I decided against it, to keep the necessary level of programming skills low to give more people the chance to implement effects.

I don't think this is a valid point. When you're creating a new effect you probably copy paste an existing one anyway :P And if your skills are this low you'd have bigger trouble implementing the effect than copy pasting the file. Please change that? And I can merge then. Don't worry about code format, I'll run it on the whole project once merged.

**Comment by andidevi** [comment]
Just to have it clear: you want to have private classes inside the factory?

**Comment by Lonami** [comment]
However it's often done, like you said.

**Comment by andidevi** [comment]
Could you supply an editorconfig with you settings?

https://stackoverflow.com/questions/35915970/how-to-export-all-my-intellij-code-styles-to-a-editorconfig-file says:
> Go to "File->Settings->Editor->Code Style". At the bottom of the right pane there is a section for Editor Config options, which now includes an "Export" button. 

It's best to put the .editorconfig to the root of the repo.
https://stackoverflow.com/questions/44694132/editorconfig-in-android-studio

Then the next try should be formatted accordingly.

**Comment by Lonami** [comment]
Noted, but I can't right now. No access to my laptop.

**Comment by andidevi** [comment]
see pull request #43

**Comment by Lonami** [comment]
Closing as #43 got merged.

**Pull request closed without merging**
