### PR TITLE
Assign bonus score if field completely cleared

### PR DESCRIPTION
**Pull request by fyfyone**
Someone I recommended this game to was telling me it would be cool to have a bonus score whenever the field is completely cleared (for more satisfaction). Because I figured this would happen quite rarely, I created this to assign as much rows as if five extra ones were cleared.

This may not be wanted, of course, as it differs from the original game. Tell me what you think - is it too much points?

### CODE REVIEW

**Comment by Lonami** [comment]
This allows me to "play safe" and clear a single row to give me as many points as it would give me to clear 6. That feels cheaty! This prevents you from risking to have an almost-filled board so that you can clear 6 by hand (it's possible, with an L piece to clear 3 horizontally and 3 vertically).

Sorry, but please if you have more ideas let me know so we can discuss :)

Good luck reaching 4 commits for hacktoberfest, this even closed should count as one!

**Comment by fyfyone** [comment]
Hm, fair point, I have not considered that. I thought it would be very satisfying to have something that occurs rarely and randomly and see that it was recognized as a special event by someone other that oneself!

Anyway, thanks for the quick reply. Good luck during hacktoberfest ;)

**Comment by Lonami** [comment]
Heh, thanks, check your progress over https://hacktoberfestchecker.herokuapp.com/

**Comment by andidevi** [comment]
Basically I like that idea, but to adress the concerns, the bonus should be locked at the beginning.

To unlock it you would have to:
either
- 2 times receive a +210 bonus
or
- fill the board to 60% at least

Having reached one of that conditions, will make it quite less probably you get the board fully cleared again.

What do you think?

**Comment by Lonami** [comment]
So upon filling say 60% of the board, if you manage to *completely* clear it again, you get a bonus. Well, that's much more interesting than just a bonus for clearing the board. It would be nice to have some kind of extra indicator for this though, so to have more feedback. Not sure how to let the user know that it means they have a bonus, or how they would understand "sometimes I get a bonus sometimes I don't". But it's a good idea.

**Comment by andidevi** [comment]
One could display a message when unlocking like 'Clear board completly for +XX'.

**Comment by Lonami** [comment]
That's a lot of words.

**Comment by fyfyone** [comment]
"Board empty bonus unlocked"?

**Comment by Lonami** [comment]
Any amount of words is a lot of words. I would prefer some icon or other kind of feedback somehow but I have no ideas currently. Just my opinion, I wouldn't put words if I can avoid them.

**Comment by andidevi** [comment]
The icon would appear at unlocking the bonus and disappear with the last cells. At this point the regular bonus text will be shown and the message will get clear.

I think it's ok to let users dig into the game before understanding everything, thats an important part of game play.

**Pull request closed without merging**
