### PR TITLE
Theme Bulbs

### PR DESCRIPTION
**Pull request by andidevi**
My nine year old son created a bulb theme (with some help from me ... but he's the artist).

The images are based on this svg: https://www.flaticon.com/free-icon/light-bulb_167745#term=light%20bulb&page=1&position=7

We would be happy to get it merged.

screenshotbulb

### CODE REVIEW

**Comment by Lonami** [comment]
That's both a cute story and interesting theme, it actually looks pretty good. Props to your son!

**Comment by Lonami** [comment]
It would be interesting to have a matching effect which somehow flashed the screen and all of a sudden the bulbs would be gone and the row cleared. I wonder how we could get around that.

**Comment by andidevi** [comment]
To have that effect you may overpaint the cell image with white or a very bright yellow. This should not be done with color multiplication used for theme colors but by setting all collor values to the absolute target.

My sons first idea has been a real explode effect, taking the image apart, or alternativly using a simple dissolve without movement. Listening to your idea, he added, having some smoke after the flash would be great. Implementing such smoke would need an additional image asset for that to define the form of that smoke. maybe it could be done with some grey paint, reduced alpha channel and individual moment of of the cell image's pixels. 

Maybe it's just ok, to have the bright flash, set to smokey grey afterwards and dissolve that without any movement. That should be somewhat easier to implement.

**Comment by Lonami** [comment]
When I first thought of adding a explossion effect it was different from what I ended up implementing (because this way it's easier). Everything else you mentioned could look great if implemented properly as well. If you're down for the challenge, it should be fairly simple. Implemented effects are [here](https://github.com/LonamiWebs/Klooni1010/tree/master/core/src/io/github/lonamiwebs/klooni/effects) and they need to do is implement the [`IEffect.java`](https://github.com/LonamiWebs/Klooni1010/blob/b0abab11ab91a8a2fb60f8a9a75d7d61e48ee6ee/core/src/io/github/lonamiwebs/klooni/effects/IEffect.java) interface:
https://github.com/LonamiWebs/Klooni1010/blob/b0abab11ab91a8a2fb60f8a9a75d7d61e48ee6ee/core/src/io/github/lonamiwebs/klooni/effects/IEffect.java#L1-L12

**Comment by andidevi** [comment]
While having been working with Java since year, I never worked with libGDX. So it will take some time, till I find time for that challange. Maybe my son will learn programming before ...

**Comment by Lonami** [comment]
Just a tiny tweak, there was a black pixel on the top left corner of nearly every image file which probably would look odd on higher resolutions and while I was at it I changed the foreground colour (sorry but grey isn't the best colour to combine). The rest is intact though.

**Comment by andidevi** [comment]
Thanks! I didn't see the black pixel as I'm a coder only and we didn't care to much about the foreground collor. focus was on bulbs and having those colors on the buttons ;)

**Pull request merged**
