### PR TITLE
Add two new themes and support for SDK-26

### PR DESCRIPTION
**Pull request by mhdsmr2**
Completes #29.
Added _vibrant_ and _material light_ themes.

### CODE REVIEW

**Comment by Lonami** [comment]
I'll review these whenever I can :)

**Comment by mhdsmr2** [comment]
Okay. Thanks a lot.

**Comment by mhdsmr2** [comment]
Please review it before Hacktober ends

**Comment by Lonami** [comment]
Of course, that's the whole point of the issue!

**Comment by Lonami** [comment]
`material-light` has a weird colour for the buttons. Such a deep **black** and the other colourful doesn't really fit. Turn that black into another colour.

`material-dark` and `vibrant` has such weird **black** *and* it also has a **white**, which doesn't show the item inside! 

And the colour for the pieces in general is very repetitive. You should run this yourself to check out how the colours really look. It looks bad! Easiest way is to "hack" the game to give yourself a lot of money and then buy them.

**Comment by mhdsmr2** [comment]
Okay. I'll run them on my emulator.

**Comment by Lonami** [comment]
Remember you can run the game on your desktop too. Setting it up with Android Studio is really easy. Would you like instructions?

**Comment by mhdsmr2** [comment]
Yeah, give me the instruction(just in case).

**Comment by Lonami** [comment]
@mhdsmr2 https://github.com/libgdx/libgdx/wiki/Gradle-and-Intellij-IDEA#running-your-project

**Comment by mhdsmr2** [comment]
Which version of build tool does Klooni1010 require?

**Comment by Lonami** [comment]
Not sure, I just use latest.

**Comment by mhdsmr2** [comment]
Oh Okay. It might be 26 then.

**Comment by mhdsmr2** [comment]
Hey, listen.
Your app doesn't support for `Android SDK - 26` (which apparently the only SDK I have). Will you mind if I make it support `SDK-26`?

**Comment by Lonami** [comment]
Isn't it enough with changing `compileSdkVersion 25` with `compileSdkVersion 26` on your `.gradle` files?

**Comment by mhdsmr2** [comment]
Yeah, I'll change it myself.
But when I am setting configurations up, in "Use classpath of module", there are only two options "Klooni1010" and "No modules", but the docs you sent says I have to select "desktop". Can you help me?

**Comment by Lonami** [comment]
image

Maybe you have to synchronize the files through gradle:
image

The middle button.

**Comment by mhdsmr2** [comment]
Okay, let me try this.

**Comment by mhdsmr2** [comment]
I updated the app to support SDK 26 and deleted material dark because it wasn't that unique. I did the best I can. Sorry if the theme doesn't look good to you.

**Comment by Lonami** [comment]
It's just the material themes were very similar, and some colours were clearly "broken" (completely black/white, icon wasn't visible!)

**Comment by mhdsmr2** [comment]
Can I create a new PR? I have done the work in my "issue#29" branch.

**Comment by Lonami** [comment]
Of course. You can also push here and updates will be reflected, then I can combine it in into one.

**Comment by mhdsmr2** [comment]
Okay. [Here](https://github.com/LonamiWebs/Klooni1010/pull/33) it is.

**Pull request closed without merging**
