### PR TITLE
Change F-Droid badge height to 80

### PR DESCRIPTION
**Pull request by mueller-ma**

### CODE REVIEW

**Comment by Poussinou** [comment]
@mueller-ma I see that you're pushing everybody to use fastlane in their repos , that's great. Ask if you need help :)

I just reviewed your PR to know how it works, no offense to you ;)

**Comment by mueller-ma** [comment]
I definitly need a lot of help for that. You can help me by opening issues on apps w/o fastlane metadata.
There are two reasons why I don't want to open too much issues like that:
1. I don't want to get blocked, because these issues can/may be considered spam.
2. I don't have the time to support app devs to add the metadata or make changes in the fdroiddata repo.

We should discuss this here: https://gitlab.com/fdroid/fdroiddata/issues/1221

**Comment by Poussinou** [comment]
I'll have a look

**Comment by Lonami** [comment]
I generally disapprove with such tiny commits being made alone. Would be nice if it could be merged with some other changes such as the suggested in #53.

**Comment by Poussinou** [comment]
I'm currently working on it

**Comment by mueller-ma** [comment]
Ok, thanks @Poussinou

**Comment by Lonami** [comment]
Thanks to you too, @mueller-ma :)

**Pull request closed without merging**
