### PR TITLE
Add fastlane

### LINKED ISSUE #53: Improve F-Droid listing
I've seen this app on F-Droid, but it lacks screenshots, changelog and a translatable description there. It's pretty easy for you to add these information. Please have a look at [this example](https://github.com/Freeyourgadget/Gadgetbridge/tree/master/fastlane/metadata/android) or at the [F-Droid docs](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository) or [fastlane docs](https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#images-and-screenshots).
After you have commited these files to your repo and tagged a new version, you need to remove the `Description` and `Summary` from the metadata file in the [F-Droid Data repo](https://gitlab.com/fdroid/fdroiddata).

### PR DESCRIPTION
**Pull request by Poussinou**
This PR adds fastlane directories. Please review this PR carefully, as this is the first time I do something like this.

The about.txt file was just a way to create the "phoneScreenshots" directory, because I couldn't find a way to directly upload the images. This file doesn't exist anymore.

+ set the size of the badge to 80
+ close #53

### CODE REVIEW

**Comment by Lonami** [comment]
There aren't a lot of changes, so it was quite straightforward to go through them :)

You added a few binary files, something I dislike, because they're not `.git`-friendly. As it was suggested on #53, using the [F-Droid Data repo](https://gitlab.com/fdroid/fdroiddata) may be a better option. Other than that, it's good.

**Comment by Lonami** [comment]
Well, the images you posted are around 100KB in total, which isn't a lot, and I don't expect changes to them. It would probably be acceptable and purging them would possibly be fine at a later point in time (they're just screenshots) if needed. We can merge if the directory tree is correct.

**Comment by Poussinou** [comment]
I double checked the tree and that's ok for me, please have a look by yourself. I also used [this repo](https://github.com/k3b/ToGoZip/tree/master/fastlane/metadata/android) to check everything was ok.

By the way I'm not sure tagging a new release is useful, I think F-Droid will just check this repo to find the fastlane directory and all stuff. We will see after this has been merged.

**Comment by Lonami** [comment]
#53 hints that we need new tag. But yes, we will see.

**Comment by Lonami** [comment]
Full description taken from [Klooni's site](https://lonamiwebs.github.io/klooni/).

**Comment by Lonami** [comment]
> Maybe you could extract hard coded strings and put them in the strings.xml file, so that I can translate them in French

The thing is, this is a libGDX game, not a normal Android application, so I'm not sure how localization or loading strings works there. I would need to look into it. Either way, I've tried to keep the game mainly string-free (notice the high use of visual icons instead strings, although some are necessary to explain parts). I could be doable, and surely some people would benefit (#50).

**Comment by Poussinou** [comment]
Yep I noticed there wasn't a lot of strings 😛 But I cannot help you...

I'm gonna wait for this PR to be merged and a new release to be tagged before pushing other fastlane directories to other F-Droid apps.

**Comment by Lonami** [comment]
To make the new version more substantial we could implement more than one asset for the cells for the theme in #34. Currently there is only one possible asset for all cells, but we could implement apples, bananas, pears, and all those fruits randomly. It surely would be fun. There would be rotten fruit, too, since colours are random :P

**Comment by Lonami** [comment]
It'd also be interesting to have #51 which is even more job, and I'm not sure when (or if) it will be done at all. It's fine to release just the screenshots, though :)

**Comment by Poussinou** [comment]
Surely it could be fun, but I'm no graphic designer xD my UI aren't the best, if you see what I mean...

**Comment by bb010g** [comment]
If you're worried about binary file size, couldn't you use LFS?

**Comment by Lonami** [comment]
LFS as its name implies is for "*Large* File Storage". I don't think it's worth the trouble for just a few extra static KB, which can be purged if things go wrong anyway.

**Pull request merged**
