### PR TITLE
Add two new themes and support for SDK-26

### LINKED ISSUE #29: Add new themes
Design and contribute your **own theme** for Klooni! The only requirement is it has to be playable and not hurt players' eyes :)

To create a new theme, clone the repository, open `themes/create-theme.html` on a browser, and start designing. Then, show me your result and if it's pleasing enough we can integrate it in the application.

You can also **modify existing themes** to make the sprites or colours more pleasing. To modify or add **new sprites**, please use [Inkscape](https://inkscape.org/).

Preferrably, provide screenshots, they will make my task easier :)

For more information about the hacktoberfest and how you can get a free shirt, check out https://hacktoberfest.digitalocean.com.

### PR DESCRIPTION
**Pull request by m-sameer**
Added support for Android SDK-26.
Added two new themes.

Closes #29

### CODE REVIEW

**Comment by Lonami** [comment]
Will check them tomorrow. Have you fixed the completely black/white buttons? Tried changing the pieces a bit more so they're more "unique"? Can you think of any new texture we could use that would fit?

**Comment by mhdsmr2** [comment]
I made them unique enough so that someone could easily distinguish.

**Comment by mhdsmr2** [comment]
Please merge them now.

**Comment by Lonami** [comment]
<table>
<tr>
<th>Default</th><th>Material Light</th>
</tr>
<tr>
<td></td>
<td><td></tr></table>

Do you see my point? Although they are different, you need to take a close look to notice they're different :(

Sorry for being so picky but it just isn't different or special enough in my opinion. And the combination used in the Vibrant one, even with the basic cell type (I don't like the snowflake I designed that much…) makes it look odd with such a dark empty cell:
image

If you're just doing this for having 4 pull requests don't worry though, closed also count (and you already [have a lot](https://hacktoberfestchecker.herokuapp.com/?username=mhdsmr2)).

**Comment by mhdsmr2** [comment]
No, I was just preparing for GCI. I have exams going on right now, so I don't have time to edit this(next exam is Hindi and I am really bad at it). The exams end on 20th October, I'll edit these theme after 20.

**Comment by Lonami** [comment]
@mhdsmr2 Okay, good luck :)

**Comment by m-sameer** [comment]
I will not be able to create a great theme so I am just closing this PR. Sorry.

**Pull request closed without merging**
